---TEACHER CANDIDATE 
let
    Source = Sql.Database("RG-DEV-JETTEST\SQL2019", "EdFi_Ods_Populated_Template3", [Query="--TEACHER CANDIDATE #(lf)SELECT tc.TeacherCandidateIdentifier#(lf)#(tab)#(tab),tc.FirstName#(lf)#(tab)#(tab),tc.LastSurname#(lf)#(tab)#(tab),tc.SexDescriptorId#(lf)#(tab)#(tab),r.RaceDescriptorId#(lf)#(tab)#(tab),tc.HispanicLatinoEthnicity#(lf)#(tab)#(tab),tc.EconomicDisadvantaged#(lf)#(tab)#(tab),c.SchoolYear as Cohort#(lf)#(tab)#(tab),tc.ProgramComplete#(lf)#(tab)#(tab),tc.StudentUSI#(lf)#(tab)#(tab),tpp.ProgramName#(lf)#(tab)#(tab),tpp.BeginDate#(lf)#(tab)#(tab),tpp.EducationOrganizationId#(lf)#(tab)#(tab),tc.PersonId#(lf)#(tab)#(tab),cred.Credentialed#(lf)#(tab)FROM [tpdm].[TeacherCandidate] tc#(lf)#(tab)JOIN tpdm.TeacherCandidateTeacherPreparationProviderProgramAssociation tpp on tpp.TeacherCandidateIdentifier = tc.TeacherCandidateIdentifier#(lf)#(tab)LEFT OUTER JOIN dbo.[tpdm.tcrace] r on tc.TeacherCandidateIdentifier = r.TeacherCandidateIdentifier#(lf)#(tab)LEFT OUTER JOIN edfi.Descriptor rd on r.RaceDescriptorI    d = rd.DescriptorId#(lf)#(tab)LEFT OUTER JOIN tpdm.TeacherCandidateCohortYear c on tc.TeacherCandidateIdentifier = c.TeacherCandidateIdentifier#(lf)#(tab)LEFT OUTER JOIN dbo.Credentialed cred on tc.TeacherCandidateIdentifier = cred.TeacherCandidateIdentifier"]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"TeacherCandidateIdentifier", type number}, {"RaceDescriptorId", Int64.Type}, {"Cohort", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,11436,Replacer.ReplaceValue,{"RaceDescriptorId"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Cohort", Int64.Type}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "Cohort Sort", each if [Cohort] = null then 1 else if [Cohort] = 2014 then 2 else if [Cohort] = 2015 then 3 else if [Cohort] = 2016 then 4 else if [Cohort] = 2017 then 5 else if [Cohort] = 2018 then 6 else if [Cohort] = 2019 then 7 else null),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Cohort Sort", Int64.Type}, {"Credentialed", type text}, {"ProgramComplete", type text}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type2","false","Not Certified",Replacer.ReplaceValue,{"Credentialed"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","true","Certified",Replacer.ReplaceValue,{"Credentialed"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","true","Complete",Replacer.ReplaceValue,{"ProgramComplete"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","false","Incomplete",Replacer.ReplaceValue,{"ProgramComplete"}),
    #"Added Conditional Column1" = Table.AddColumn(#"Replaced Value4", "ProgramNameSort", each if Text.StartsWith([ProgramName], "All Level") then 1 else if Text.StartsWith([ProgramName], "Elementary") then 2 else if Text.StartsWith([ProgramName], "Middle School") then 3 else if Text.StartsWith([ProgramName], "High School") then 4 else null),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"ProgramNameSort", Int64.Type}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type3"),
    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "FullName", each [FirstName]&" "&[LastSurname]),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom",{{"FullName", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type4",{{"Credentialed", "Certification Status"}})
in
    #"Renamed Columns"

--------------------------------------------------------------
--------------------------------------------------------------

---TPP
let
    Source = Sql.Database("RG-DEV-JETTEST\SQL2019", "EdFi_Ods_Populated_Template3", [Query="---TPP#(lf)SELECT EducationOrganizationId#(lf)#(tab)#(tab),NameOfInstitution #(lf)#(tab)FROM edfi.EducationOrganization"])
in
    Source

--------------------------------------------------------------
--------------------------------------------------------------


---Race
let
    Source = Sql.Database("RG-DEV-JETTEST\SQL2019", "EdFi_Ods_Populated_Template3", [Query="---Race Dimension#(lf)SELECT DISTINCT r.RaceDescriptorId#(lf)#(tab)#(tab),d.CodeValue #(lf)#(tab)FROM dbo.[tpdm.tcrace] r#(lf)#(tab)LEFT OUTER JOIN edfi.Descriptor d on d.DescriptorId = r.RaceDescriptorId"]),
    #"Renamed Columns" = Table.RenameColumns(Source,{{"CodeValue", "Race"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"RaceDescriptorId", Int64.Type}})
in
    #"Changed Type"

--------------------------------------------------------------
--------------------------------------------------------------

---Sex
let
    Source = Sql.Database("RG-DEV-JETTEST\SQL2019", "EdFi_Ods_Populated_Template3", [Query="---Sex#(lf)SELECT S.SexDescriptorId#(lf)#(tab)#(tab), D.CodeValue #(lf)#(tab)FROM edfi.SexDescriptor S#(lf)#(tab)LEFT OUTER JOIN edfi.Descriptor d on d.DescriptorId = S.SexDescriptorId"]),
    #"Renamed Columns" = Table.RenameColumns(Source,{{"CodeValue", "Sex"}})
in
    #"Renamed Columns"

--------------------------------------------------------------
--------------------------------------------------------------

---Financial Aid
let
    Source = Sql.Database("RG-DEV-JETTEST\SQL2019", "EdFi_Ods_Populated_Template3", [Query="---Financial Aid#(lf)SELECT a.TeacherCandidateIdentifier#(lf)#(tab)#(tab),a.BeginDate#(lf)#(tab)#(tab),a.EndDate#(lf)#(tab)#(tab),a.AidConditionDescription#(lf)#(tab)#(tab),d.CodeValue as AidType#(lf)#(tab)#(tab),a.AidAmount#(lf)#(tab)#(tab),a.PellGrantRecipient#(lf)  FROM tpdm.TeacherCandidateAid a#(lf)  LEFT OUTER JOIN edfi.Descriptor d on a.AidTypeDescriptorId = d.DescriptorId"]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"BeginDate", type date}, {"EndDate", type date}, {"TeacherCandidateIdentifier", type number}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,false,Replacer.ReplaceValue,{"PellGrantRecipient"})
in
    #"Replaced Value"

--------------------------------------------------------------
--------------------------------------------------------------

---EVALUATION RATING RESULT
let
    Source = Sql.Database("RG-DEV-JETTEST\SQL2019", "EdFi_Ods_Populated_Template3", [Query="---EVALUATION RATING RESULT#(lf)SELECT tc.TeacherCandidateIdentifier#(lf)#(tab)#(tab),err.EvaluationDate#(lf)#(tab)#(tab),err.EvaluationTitle#(lf)#(tab)#(tab),err.Rating#(lf)#(tab)#(tab),err.RatingResultTitle#(lf)#(tab)FROM tpdm.EvaluationRatingResult err#(lf)#(tab)JOIN tpdm.TeacherCandidate tc on err.PersonId = tc.PersonId"]),
    #"Filtered Rows" = Table.SelectRows(Source, each ([RatingResultTitle] = "Overall Score"))
in
    #"Filtered Rows"

--------------------------------------------------------------
--------------------------------------------------------------